const veriHavuzu = [
  { soru: "merhaba", cevap: "Merhaba! Sana nasıl yardımcı olabilirim?" },
  { soru: "nasılsın", cevap: "Ben her zaman çalışmaya hazırım. Sen nasılsın?" },
  { soru: "hava durumu", cevap: "Hava durumu değişebilir, en güncel bilgiler için meteoroloji sitelerine göz atabilirsin." },
  { soru: "cumhuriyet ne zaman ilan edildi", cevap: "Cumhuriyet 29 Ekim 1923 tarihinde ilan edildi." },
  { soru: "ataturk kimdir", cevap: "Mustafa Kemal Atatürk, Türkiye Cumhuriyeti'nin kurucusudur." },
  { soru: "en büyük gezegen", cevap: "Güneş Sistemi'ndeki en büyük gezegen Jüpiter'dir." },
  { soru: "türkiye'nin başkenti", cevap: "Türkiye'nin başkenti Ankara'dır." },
  { soru: "en uzun nehir", cevap: "Nil Nehri, dünyanın en uzun nehridir." },
  { soru: "istanbul hangi kıtada", cevap: "İstanbul hem Avrupa hem Asya kıtasında yer alır." },
  { soru: "dünyanın uydusu", cevap: "Dünya'nın doğal uydusu Ay'dır." },
  { soru: "python nedir", cevap: "Python, basit ve güçlü bir programlama dilidir." },
  { soru: "java nedir", cevap: "Java, nesne yönelimli ve platformdan bağımsız bir programlama dilidir." },
  { soru: "kodlama nedir", cevap: "Kodlama, bilgisayarlara ne yapacağını anlatan komutları yazmaktır." },
  { soru: "algoritma ne demek", cevap: "Algoritma, belirli bir problemi çözmek için izlenen adımlar dizisidir." },
  { soru: "bilgisayar nasıl çalışır", cevap: "Bilgisayar, veri alır, işler ve çıktı üretir; yazılım ve donanım birlikte çalışır." },
  { soru: "güneş sistemi", cevap: "Güneş Sistemi, Güneş ve etrafında dönen gezegenlerden oluşur." },
  { soru: "gezegenler", cevap: "Merkür, Venüs, Dünya, Mars, Jüpiter, Satürn, Uranüs ve Neptün." },
  { soru: "en hızlı hayvan", cevap: "Karada çita, havada ise alaca doğan en hızlı hayvanlardır." },
  { soru: "en büyük deniz", cevap: "Filipin Denizi, yüzölçümü bakımından en büyük denizdir." },
  { soru: "kıta nedir", cevap: "Dünyadaki büyük kara parçalarına kıta denir. Örnek: Asya, Avrupa, Afrika." },
  { soru: "en uzun dağ", cevap: "Everest Dağı, deniz seviyesinden yüksekliğiyle en uzun dağdır." },
  { soru: "en derin okyanus", cevap: "Pasifik Okyanusu en derin okyanustur, Mariana Çukuru içinde yer alır." },
  { soru: "atom nedir", cevap: "Atom, maddenin en küçük yapı taşıdır." },
  { soru: "enerji nedir", cevap: "Enerji, iş yapabilme yeteneğidir." },
  { soru: "ışık hızı", cevap: "Işık saniyede yaklaşık 300.000 kilometre hızla gider." },
  { soru: "dünyanın şekli", cevap: "Dünya, geoid adı verilen hafif basık bir küre şekline sahiptir." },
  { soru: "dünya kaç yaşında", cevap: "Yaklaşık 4.5 milyar yaşındadır." },
  { soru: "matematik ne işe yarar", cevap: "Mantıklı düşünmeyi, problem çözmeyi ve hesaplamayı öğretir." },
  { soru: "kimya nedir", cevap: "Kimya, maddelerin yapısını ve etkileşimlerini inceleyen bilim dalıdır." },
  { soru: "biyoloji nedir", cevap: "Biyoloji, canlıları inceleyen bilim dalıdır." },
  { soru: "fizik nedir", cevap: "Fizik, madde ve enerjinin doğasını ve etkileşimini inceler." },
  { soru: "ingilizce ne işe yarar", cevap: "Dünya genelinde iletişim kurmak ve kaynaklara erişmek için kullanılır." },
  { soru: "dil nedir", cevap: "Dil, insanların duygu ve düşüncelerini ifade etme aracıdır." },
  { soru: "tarih nedir", cevap: "Geçmişteki olayları inceleyen sosyal bilim dalıdır." },
  { soru: "coğrafya neyi inceler", cevap: "Yeryüzü şekilleri, iklim, yerleşim ve insan faaliyetlerini inceler." },
  { soru: "bilgisayar bileşenleri nelerdir", cevap: "İşlemci, RAM, sabit disk, ekran kartı, anakart gibi donanımlardır." },
  { soru: "saat kaç", cevap: "Benim saatim yok ama cihazının saati doğrudur 😊" },
  { soru: "günün sözü", cevap: "Başlamak için mükemmel olmayı bekleme, mükemmel olmak için başla." },
  { soru: "en çok konuşulan dil", cevap: "Çince, ardından İspanyolca ve İngilizce gelir." },
  { soru: "en büyük ülke", cevap: "Yüzölçümüne göre Rusya en büyük ülkedir." },
  { soru: "en küçük ülke", cevap: "Vatikan, hem yüzölçümü hem nüfus bakımından en küçüktür." },
  { soru: "en uzun köprü", cevap: "Çin'deki Danyang–Kunshan Grand Köprüsü'dür." },
  { soru: "en hızlı tren", cevap: "Japonya’daki Maglev trenleri 600 km/s üzerine çıkabilir." },
  { soru: "en derin göl", cevap: "Baykal Gölü, dünyanın en derin tatlı su gölüdür." },
  { soru: "amazon ormanı", cevap: "Dünyanın en büyük yağmur ormanıdır." },
  { soru: "kutup ayısı nerede yaşar", cevap: "Kuzey Kutbu bölgesinde yaşar." },
  { soru: "penguen nerede yaşar", cevap: "Güney Kutbu ve çevresindeki bölgelerde yaşar." },
  { soru: "en yüksek bina", cevap: "Burj Khalifa, 828 metre yüksekliğiyle en uzundur." },
  { soru: "dünyanın merkezi", cevap: "Bilimsel olarak bir merkezi yoktur, Dünya küreseldir." },
  { soru: "güneş nedir", cevap: "Güneş, hidrojen gazı yakan dev bir yıldızdır." },
  { soru: "dünya ne zaman oluştu", cevap: "Yaklaşık 4.5 milyar yıl önce oluşmuştur." },
  { soru: "türkiye kaç bölgeden oluşur", cevap: "Türkiye 7 coğrafi bölgeden oluşur." },
  { soru: "türkiye'nin komşuları", cevap: "Yunanistan, Bulgaristan, Gürcistan, Ermenistan, Azerbaycan, İran, Irak, Suriye." },
  { soru: "istanbul boğazı neyi ayırır", cevap: "Asya ve Avrupa kıtalarını ayırır." },
  { soru: "boğaz köprüleri", cevap: "15 Temmuz Şehitler, Fatih Sultan Mehmet ve Yavuz Sultan Selim köprüleri." },
  { soru: "atatürk'ün doğum yılı", cevap: "1881 yılında doğmuştur." },
  { soru: "atatürk'ün ölüm yılı", cevap: "10 Kasım 1938'de vefat etmiştir." },
  { soru: "cumhuriyet nedir", cevap: "Halkın kendi kendini yönettiği yönetim biçimidir." },
  { soru: "demokrasi nedir", cevap: "Halkın seçtiği temsilciler aracılığıyla yönetimdir." },
  { soru: "seçim nedir", cevap: "Vatandaşların yöneticileri belirlemek için oy kullandığı süreçtir." },
  { soru: "oy kullanma yaşı", cevap: "Türkiye'de oy kullanma yaşı 18'dir." },
  { soru: "meclis nedir", cevap: "Yasaların yapıldığı, milletvekillerinden oluşan kuruldur." },
  { soru: "anayasa nedir", cevap: "Devletin temel kanunu, hak ve özgürlükleri belirler." },
  { soru: "bayrak neyi simgeler", cevap: "Bağımsızlığı, milleti ve tarihi değerleri simgeler." },
  { soru: "istiklal marşı", cevap: "Türkiye Cumhuriyeti'nin milli marşıdır. Sözleri Mehmet Akif Ersoy'a aittir." },
  { soru: "türkiye'nin yüzölçümü", cevap: "Yaklaşık 783.562 kilometrekaredir." },
  { soru: "en uzun nehir türkiye", cevap: "Kızılırmak, Türkiye'nin en uzun nehridir." },
  { soru: "büyük şehirler", cevap: "İstanbul, Ankara, İzmir, Bursa, Adana, Antalya gibi iller." },
  { soru: "türkiye nüfusu", cevap: "2023 itibarıyla yaklaşık 85 milyon kişidir." },
  { soru: "ayasofya nedir", cevap: "İstanbul'da bulunan tarihi bir cami ve müzedir." },
  { soru: "kapadokya nerede", cevap: "Nevşehir ve çevresinde yer alır." },
  { soru: "pamukkale nerede", cevap: "Denizli ilinde bulunur." },
  { soru: "efes antik kenti", cevap: "İzmir’in Selçuk ilçesinde yer alan tarihi kent." },
  { soru: "nemrut dağı", cevap: "Adıyaman'da tarihi heykelleriyle ünlü bir dağdır." },
  { soru: "ilk çağ nedir", cevap: "Yazının icadıyla başlayıp Roma İmparatorluğu’nun yıkılışına kadar süren dönemdir." },
  { soru: "orta çağ", cevap: "Roma'nın yıkılışından İstanbul’un fethine kadar olan dönemdir (476–1453)." },
  { soru: "yeni çağ", cevap: "1453’ten Fransız İhtilali’ne kadar olan dönemdir." },
  { soru: "yakın çağ", cevap: "1789 Fransız İhtilali ile başlayıp günümüze kadar süren dönemdir." },
  { soru: "kurtuluş savaşı", cevap: "Türkiye'nin 1919–1923 arasında verdiği bağımsızlık savaşıdır." },
  { soru: "çanakkale savaşı", cevap: "I. Dünya Savaşı sırasında 1915’te Osmanlı'nın kazandığı büyük zaferdir." },
  { soru: "istanbul'un fethi", cevap: "Fatih Sultan Mehmet tarafından 1453 yılında gerçekleşmiştir." },
  { soru: "fatih sultan mehmet kimdir", cevap: "Osmanlı padişahı, İstanbul'u fethederek çağ kapatıp çağ açmıştır." },
  { soru: "kanuni sultan süleyman", cevap: "Osmanlı'nın en uzun süre tahtta kalan ve en çok sefer düzenleyen padişahıdır." },
  { soru: "osmanlı devleti ne zaman kuruldu", cevap: "1299 yılında Osman Gazi tarafından kuruldu." },
  { soru: "osmanlı devleti ne zaman yıkıldı", cevap: "1922 yılında saltanat kaldırılmasıyla sona erdi." },
  { soru: "tanzimat dönemi", cevap: "Osmanlı'da 1839–1876 arası reformların yapıldığı dönemdir." },
  { soru: "meşrutiyet nedir", cevap: "Padişahın yetkileri anayasayla sınırlandığı yönetim şeklidir." },
  { soru: "harf devrimi", cevap: "1928'de Latin alfabesinin kabulüyle gerçekleşmiştir." },
  { soru: "kadınlara seçme hakkı", cevap: "1934 yılında tanındı, Avrupa'daki birçok ülkeden önce." },
  { soru: "soyadı kanunu", cevap: "1934'te herkesin bir soyadı almasını zorunlu kılan yasadır." },
  { soru: "cumhurbaşkanı kimdir", cevap: "Devletin en üst düzey yöneticisidir." },
  { soru: "başbakan nedir", cevap: "2018’den sonra Türkiye’de başbakanlık kaldırılmıştır." },
  { soru: "bakanlar kurulu", cevap: "Eski sistemde yürütmenin başıdır, artık yoktur." },
  { soru: "milletvekili nedir", cevap: "TBMM'de halkı temsil eden kişilerdir." },
  { soru: "vali kimdir", cevap: "İlin en yetkili devlet temsilcisidir, atamayla göreve gelir." },
  { soru: "belediye başkanı", cevap: "Halk tarafından seçilir, belediyeyi yönetir." },
  { soru: "nüfus cüzdanı", cevap: "Kimlik bilgilerini taşıyan resmi belgedir." },
  { soru: "pasaport nedir", cevap: "Yurt dışına çıkarken kullanılan resmi belgedir." },
  { soru: "ehliyet nasıl alınır", cevap: "Sürücü kursuna kayıt olup sınavları geçerek ehliyet alınır." },
  { soru: "ilk yardım nedir", cevap: "Acil durumda sağlık ekipleri gelene kadar yapılan müdahaledir." },
  { soru: "yangın anında ne yapılmalı", cevap: "Panik yapmadan tahliye edilmeli ve itfaiye aranmalıdır: 110." },
  { soru: "ambulans numarası", cevap: "Acil durumlar için 112'yi aramalısın." },
  { soru: "polis numarası", cevap: "Polis için 155 numaralı hattı arayabilirsin." },
  { soru: "jandarma numarası", cevap: "156 numarası jandarma içindir." },
  { soru: "zehirlenme hattı", cevap: "114 numaralı Ulusal Zehir Danışma Merkezi." },
  { soru: "trafik kuralları neden önemli", cevap: "Kazaları önlemek ve can güvenliğini sağlamak için gereklidir." },
  { soru: "trafik lambaları ne işe yarar", cevap: "Araç ve yaya akışını güvenli şekilde yönlendirir." },
  { soru: "yaya geçidi nedir", cevap: "Yayaların güvenli geçişi için ayrılmış yol bölümüdür." },
  { soru: "hız sınırı ne demek", cevap: "Araçların yolda uyması gereken azami hız değeridir." },
  { soru: "hız limiti ne kadar", cevap: "Yerleşim yerinde genellikle 50 km/s, otoyollarda 120 km/s’tir." },
  { soru: "trafikte emniyet kemeri", cevap: "Kazalarda yaralanma riskini büyük ölçüde azaltır." },
  { soru: "ehliyet türleri", cevap: "B, A1, C, D gibi sınıflar farklı araçlar içindir." },
  { soru: "alkollü araç kullanma", cevap: "Yasaktır ve ciddi cezalara yol açar." },
  { soru: "trafik işaret levhaları", cevap: "Sürücülere bilgi, uyarı ve yasaklama mesajları verir." },
  { soru: "yeşil ışıkta ne yapılır", cevap: "Geçiş serbesttir, dikkatli ilerlenir." },
  { soru: "kırmızı ışıkta ne yapılır", cevap: "Durulur ve yeşil ışık beklenir." },
  { soru: "sarı ışık ne anlama gelir", cevap: "Hazır ol veya dikkatli ol anlamındadır." },
  { soru: "sürüş güvenliği", cevap: "Kurallara uymak, dikkatli olmak ve yorgun araç kullanmamak önemlidir." },
  { soru: "araç bakımı neden önemli", cevap: "Emniyetli sürüş ve yakıt tasarrufu için gereklidir." },
  { soru: "akü ne işe yarar", cevap: "Araçta elektrik sistemini ve çalıştırmayı sağlar." },
  { soru: "motor yağı değişimi", cevap: "Motorun sağlıklı çalışması için düzenli olarak yapılmalıdır." },
  { soru: "lastik basıncı neden önemli", cevap: "Yol tutuşu, frenleme ve yakıt tüketimini etkiler." },
  { soru: "araç muayenesi", cevap: "Belirli aralıklarla yapılan yasal zorunlu teknik kontroldür." },
  { soru: "ruhsat nedir", cevap: "Aracın kayıtlı olduğunu ve teknik bilgilerini içeren belgedir." },
  { soru: "kasko nedir", cevap: "Araçta oluşan hasarlara karşı yapılan isteğe bağlı sigortadır." },
  { soru: "zorunlu trafik sigortası", cevap: "Kaza durumunda karşı tarafın zararını karşılayan yasal sigortadır." },
  { soru: "yakıt tasarrufu nasıl sağlanır", cevap: "Yumuşak sürüş, düzenli bakım ve doğru lastik basıncıyla olur." },
  { soru: "emniyet kemeri kullanmazsam", cevap: "Kaza durumunda hayati risk artar, ayrıca ceza alınır." },
  { soru: "araba çalışmazsa ne yapılmalı", cevap: "Akü kontrol edilmeli, gerekirse takviye yapılmalı ya da servis çağrılmalı." },
  { soru: "araç radyatörü nedir", cevap: "Motorun ısısını kontrol eden parçalardan biridir." },
  { soru: "motor hararet yaparsa", cevap: "Aracın güvenli bir yere çekilip motorun soğuması beklenmeli, su seviyesi kontrol edilmeli." },
  { soru: "araba neden stop eder", cevap: "Yakıt bitmesi, motor arızası veya elektronik sorunlar gibi nedenlerle olabilir." },
  { soru: "vites ne işe yarar", cevap: "Motor gücünü tekerleklere iletir ve hız kontrolünü sağlar." },
  { soru: "otomatik vites nedir", cevap: "Vites geçişlerini sürücü yerine araç otomatik yapar." },
  { soru: "manuel vites nedir", cevap: "Vites geçişleri sürücü tarafından yapılır." },
  { soru: "araba nasıl park edilir", cevap: "Dikkatlice manevra yaparak boş alana hizalanır, el freni çekilir." },
  { soru: "el freni ne işe yarar", cevap: "Araç dururken kaymasını engeller." },
  { soru: "farlar neden önemlidir", cevap: "Gece görüşü sağlar ve diğer araçlar tarafından fark edilmeni sağlar." },
  { soru: "uzun far ne zaman açılır", cevap: "Karşıdan araç yokken ve yeterli aydınlatma olmadığında kullanılır." },
  { soru: "sinyal vermek ne işe yarar", cevap: "Diğer sürücüleri yön değişikliklerinden haberdar eder." },
  { soru: "trafikte saygı", cevap: "Herkesin güvenliği için vazgeçilmez bir ilkedir." },
  { soru: "trafik kazası nedir", cevap: "Yollarda meydana gelen, can veya mal kaybına neden olan olaylardır." },
  { soru: "trafik kazasında ne yapılır", cevap: "Yaralı varsa 112 aranır, emniyet alınır ve tutanak tutulur." },
  { soru: "ilk yardım çantası", cevap: "Araçlarda bulundurulması zorunlu sağlık malzemeleridir." },
  { soru: "yangın tüpü neden taşınır", cevap: "Araçta çıkabilecek yangına müdahale için gereklidir." },
  { soru: "cam suyu nedir", cevap: "Ön camın temizlenmesini sağlayan sıvıdır." },
  { soru: "silecek çalışmıyor", cevap: "Sigorta kutusu, motoru ya da silecek lastiği kontrol edilmelidir." },
  { soru: "fren mesafesi neye bağlıdır", cevap: "Hız, yol durumu, fren sistemi ve lastiklere bağlıdır." },
