const veriHavuzu = [
  { soru: "merhaba", cevap: "Merhaba! Sana nasıl yardımcı olabilirim?" },
  { soru: "nasılsın", cevap: "Ben hep iyiyim, sen nasılsın?" },
  { soru: "hava durumu", cevap: "Hava durumu için en güncel bilgileri Meteoroloji sitesinden kontrol edebilirsin." },
  { soru: "cumhuriyet ne zaman ilan edildi", cevap: "29 Ekim 1923 tarihinde." },
  { soru: "türkiye'nin başkenti", cevap: "Ankara, Türkiye'nin başkentidir." },
  { soru: "en büyük gezegen", cevap: "Güneş Sistemi'nde en büyük gezegen Jüpiter'dir." },
  { soru: "ataturk kimdir", cevap: "Mustafa Kemal Atatürk, Türkiye Cumhuriyeti'nin kurucusudur." },
  { soru: "en uzun nehir", cevap: "Nil Nehri, dünyanın en uzun nehridir." },
  { soru: "istanbul hangi kıtada", cevap: "Hem Avrupa hem Asya kıtasında bulunur." },
  { soru: "dünyanın uydusu", cevap: "Ay, dünyanın doğal uydusudur." },
{ soru: "güneş sistemi", cevap: "Güneş Sistemi, Güneş ve onun etrafında dönen gezegenleri kapsar." },
  { soru: "gezegenler", cevap: "Güneş Sistemi'nin gezegenleri: Merkür, Venüs, Dünya, Mars, Jüpiter, Satürn, Uranüs, Neptün." },
  { soru: "venüs", cevap: "Venüs, Güneş'e en yakın ikinci gezegendir." },
  { soru: "mars", cevap: "Mars, kırmızı gezegen olarak bilinir ve Dünya'ya benzerliğiyle dikkat çeker." },
  { soru: "ay", cevap: "Ay, Dünya'nın tek doğal uydusudur." },
  { soru: "en hızlı hayvan", cevap: "Çita karada en hızlı hayvandır, saatte 100 km'ye kadar ulaşabilir." },
  { soru: "en büyük deniz", cevap: "Filipin Denizi, yüzölçümüne göre en büyük denizdir." },
  { soru: "kıta nedir", cevap: "Kıta, geniş kara parçalarına verilen isimdir, örneğin Asya, Afrika, Avrupa." },
  { soru: "en uzun dağ", cevap: "Everest Dağı, deniz seviyesinden yüksekliğiyle en uzun dağdır." },
  { soru: "en derin okyanus", cevap: "Pasifik Okyanusu en derin okyanustur, Mariana Çukuru içinde yer alır." },
  { soru: "nüfus nedir", cevap: "Nüfus, bir alanda yaşayan insan sayısını ifade eder." },
  { soru: "türkiye'nin nüfusu", cevap: "2023 itibarıyla yaklaşık 85 milyon civarındadır." },
  { soru: "en kalabalık ülke", cevap: "Hindistan, dünya nüfusunda zirvede yer almaktadır." },
  { soru: "bilgisayar nedir", cevap: "Bilgisayar, veri işlemek ve bilgi üretmek için kullanılan elektronik cihazdır." },
  { soru: "internet nasıl çalışır", cevap: "İnternet, dünya genelinde bağlı cihazların veri alışverişi yaptığı büyük bir ağdır." },
  { soru: "yazılım nedir", cevap: "Yazılım, bilgisayarda çalışan programların tümüne verilen addır." },
  { soru: "donanım nedir", cevap: "Donanım, bilgisayarın elle tutulabilen fiziksel parçalarıdır." },
  { soru: "html nedir", cevap: "HTML, web sayfalarının iskeletini oluşturan işaretleme dilidir." },
  { soru: "css nedir", cevap: "CSS, HTML içeriğinin görsel tasarımını düzenleyen stil dilidir." },
  { soru: "javascript nedir", cevap: "JavaScript, web sayfalarına etkileşim kazandıran programlama dilidir." },